### ISSUE TITLE
PostgreSQL: Connection refused

### ISSUE THREAD

**Issue by mamadaliev** [egnaf/spring-boot-docker-examples#29]
If, when you start the application, you get this error:
```
PostgreSQL: Connection refused
```
then most likely you should:

**1.** Remove all containers and images.
**2.** Check `application.yml` file:
```yaml
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/demo?createDatabaseIfNotExist=true
    username: root
    password: root
```

Where **postgres** is the service name in docker-compose.yml

**3.** Disable postgres on the computer if it worked.
